# docker-compose.yaml
services:
    # nginx
    web:
        image: nginx:latest
        container_name: www_docker_nginx
        ports:
            - "8256:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            -  /var/www/html/vendor
            - ./app:/var/www/html
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3310:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
    # redis
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_php
        restart: always
        depends_on:
            - db
        ports:
            - 8254:80
        environment:
            PMA_HOST: db
            
volumes:
    mysqldata:
   

